/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TvwUORqox8e
 */
import { Button } from "@/components/ui/button"
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import Link from 'next/link';
import Image from 'next/image';

export function About() {
  return (

    <><div key="1" className="bg-white">
      <nav className="bg-white py-4 shadow-md sticky top-0 z-10">
        <div className="container mx-auto px-4 flex justify-between items-center">
          {/* Replace 'Eden' with the Eden logo */}
          <Image src="/eden.jpg"
            alt="Eden Logo"
            className="h-8"
            width={20}
            height={30} />
          <div className="flex items-center space-x-4">
            <Link className="text-gray-600 hover:text-gray-800" href="/">
              Home
            </Link>
            <Link className="text-gray-600 hover:text-gray-800" href="/about">
              About Us
            </Link>
            <Link className="text-gray-600 hover:text-gray-800" href="/gallery">
              Gallery
            </Link>
            <Button className="bg-blue-500 hover:bg-blue-700 text-white">Contact Us</Button>
          </div>
        </div>
      </nav>
      <section className="bg-[#f1f5f9] text-center py-16">
        <h1 className="text-4xl font-bold text-[#1e293b]">About Us 2</h1>
        <p className="text-[#64748b] mt-2">Helping / About us</p>
      </section>
      <section className="container mx-auto px-4 py-16">
        <div className="text-center space-y-4">
          <h2 className="text-3xl font-bold text-[#1e293b]">About Us</h2>
          <p className="text-lg text-[#64748b]">We are In a Mission to Help the Helpless</p>
          <p className="text-[#64748b]">
            There are many variations of passages of lorem ipsum available, but the majority have suffered alteration in
            some form.
          </p>
          <p className="text-[#64748b]">
            Raised Fund 72% Expectation in Countries, Benefiting Over 2.5 Million People.
          </p>
          <div className="flex justify-center space-x-4">
            <Button className="bg-[#ef4444] text-white">CONTACT EDEN</Button>
            <Button className="bg-[#f97316] text-white">Volunteer</Button>
          </div>
        </div>
      </section>
      {/* <section className="container mx-auto px-4 py-16">
        <h3 className="text-2xl font-bold text-center text-[#1e293b] mb-8">Contribution Towards Countries</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <Card className="w-full bg-white">
            <CardContent>
              <FlagIcon className="text-[#ef4444] w-6 h-6" />
              <h4 className="text-lg font-semibold mt-2">United States</h4>
              <p className="text-[#64748b]">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </CardContent>
            <CardFooter className="flex justify-center">
              <Button variant="ghost">View More</Button>
            </CardFooter>
          </Card>
          <Card className="w-full bg-white">
            <CardContent>
              <FlagIcon className="text-[#ef4444] w-6 h-6" />
              <h4 className="text-lg font-semibold mt-2">France Paris</h4>
              <p className="text-[#64748b]">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </CardContent>
            <CardFooter className="flex justify-center">
              <Button variant="ghost">View More</Button>
            </CardFooter>
          </Card>
          <Card className="w-full bg-white">
            <CardContent>
              <FlagIcon className="text-[#ef4444] w-6 h-6" />
              <h4 className="text-lg font-semibold mt-2">India</h4>
              <p className="text-[#64748b]">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </CardContent>
            <CardFooter className="flex justify-center">
              <Button variant="ghost">View More</Button>
            </CardFooter>
          </Card>
          <Card className="w-full bg-white">
            <CardContent>
              <FlagIcon className="text-[#ef4444] w-6 h-6" />
              <h4 className="text-lg font-semibold mt-2">UAE Dubai</h4>
              <p className="text-[#64748b]">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </CardContent>
            <CardFooter className="flex justify-center">
              <Button variant="ghost">View More</Button>
            </CardFooter>
          </Card>
        </div>
      </section> */}
      <section className="container mx-auto px-4 py-16">
        <div className="text-center space-y-4">
          <h2 className="text-3xl font-bold text-[#1e293b]">Our Team</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
            <Card className="bg-white">
              <CardContent>
                <Avatar>
                  <AvatarImage alt="Team Member 1" src="/placeholder.svg?height=200&width=200" />
                  <AvatarFallback>TM</AvatarFallback>
                </Avatar>
                <p className="text-[#64748b] mt-2">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua.
                </p>
              </CardContent>
            </Card>
            <Card className="bg-white">
              <CardContent>
                <Avatar>
                  <AvatarImage alt="Team Member 2" src="/placeholder.svg?height=200&width=200" />
                  <AvatarFallback>TM</AvatarFallback>
                </Avatar>
                <p className="text-[#64748b] mt-2">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua.
                </p>
              </CardContent>
            </Card>
            <Card className="bg-white">
              <CardContent>
                <Avatar>
                  <AvatarImage alt="Team Member 3" src="/placeholder.svg?height=200&width=200" />
                  <AvatarFallback>TM</AvatarFallback>
                </Avatar>
                <p className="text-[#64748b] mt-2">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua.
                </p>
              </CardContent>
            </Card>
            <Card className="bg-white">
              <CardContent>
                <Avatar>
                  <AvatarImage alt="Team Member 4" src="/placeholder.svg?height=200&width=200" />
                  <AvatarFallback>TM</AvatarFallback>
                </Avatar>
                <p className="text-[#64748b] mt-2">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua.
                </p>
              </CardContent>
            </Card>
            <Card className="bg-white">
              <CardContent>
                <Avatar>
                  <AvatarImage alt="Team Member 5" src="/placeholder.svg?height=200&width=200" />
                  <AvatarFallback>TM</AvatarFallback>
                </Avatar>
                <p className="text-[#64748b] mt-2">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                  dolore magna aliqua.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
    <footer className="bg-[#1e293b] text-white py-8">
        <div className="container mx-auto px-4 text-center">
          <p>© 2024 EDEN. All rights reserved.</p>
        </div>
      </footer>
      </>
  )
}


function FlagIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}
