/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/myXamEiGtbh
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <div key="1" className="bg-white">
      <nav className="bg-gray-200 py-4">
        <div className="container mx-auto flex justify-between items-center px-6">
          <div className="flex items-center space-x-4">
            <a className="text-xl font-semibold text-gray-800" href="#">
              Eden
            </a>
            <div className="hidden md:flex space-x-2">
              <a className="text-gray-600 hover:text-gray-800" href="#">
                Home
              </a>
              <a className="text-gray-600 hover:text-gray-800" href="#">
                About Us
              </a>
              <a className="text-gray-600 hover:text-gray-800" href="#">
                Gallery
              </a>
            </div>
          </div>
          <Button className="bg-blue-600 text-white">Contact Us</Button>
        </div>
      </nav>
      <header
        className="bg-cover bg-center h-[600px] text-white"
        style={{
          backgroundImage: "\"url('/placeholder.svg')\"",
        }}
      >
        <div className="container mx-auto px-6 py-24">
          <h1 className="text-5xl font-bold mb-4">We Help You</h1>
          <h2 className="text-3xl mb-8">SAVE THE CHILDRENS.</h2>
          <p className="mb-8">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incididunt ut labore et dolore
            magna aliqua nostrud.
          </p>
          <div className="flex space-x-4">
            <Button className="bg-red-600">Donate Now</Button>
            <Button className="bg-transparent border border-white">Contact Us</Button>
          </div>
        </div>
      </header>
      <section className="container mx-auto px-6 py-12">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <img
            alt="Enriching Lives Image"
            className="aspect-[3/2] object-cover rounded-lg"
            height={400}
            src="/placeholder.svg"
            width={600}
          />
          <Card className="w-full">
            <CardContent>
              <h3 className="text-2xl font-bold mb-4">Enriching Lives</h3>
              <p className="mb-4">
                Enriching lives is at the core of our mission. We strive to make a positive impact by providing
                essential support and resources to those in need, fostering growth and empowerment in communities
                worldwide.
              </p>
              <p className="mb-4">Join us in our journey to create a brighter future for all.</p>
              <Button className="bg-red-600">Donate Now</Button>
            </CardContent>
          </Card>
        </div>
      </section>
      <section className="bg-orange-500 text-white py-12">
        <div className="container mx-auto px-6 text-center">
          <h2 className="text-4xl font-bold mb-6">Help Today Because Tomorrow you may be Needs someone help</h2>
          <Button className="bg-transparent border border-white">Watch Video</Button>
        </div>
      </section>
      <section className="container mx-auto px-6 py-12">
        <h2 className="text-3xl font-bold text-center mb-12">Our Goal</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card className="w-full">
            <CardContent>
              <h3 className="text-xl font-bold mb-4">Donate Money</h3>
              <p className="mb-4">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua.
              </p>
              <p className="mb-4">$2,000.00 donated of $15,000.00 goal</p>
              <Button className="bg-red-600">Donate</Button>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardContent>
              <h3 className="text-xl font-bold mb-4">Handle With Care</h3>
              <p className="mb-4">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua.
              </p>
              <p className="mb-4">$8,500.00 donated of $18,000.00 goal</p>
              <Button className="bg-red-600">Donate</Button>
            </CardContent>
          </Card>
          <Card className="w-full">
            <CardContent>
              <h3 className="text-xl font-bold mb-4">Be A Volunteer</h3>
              <p className="mb-4">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua.
              </p>
              <p className="mb-4">$7,500.00 donated of $13,000.00 goal</p>
              <Button className="bg-red-600">Donate</Button>
            </CardContent>
          </Card>
        </div>
      </section>
      <section className="bg-gray-100 py-12">
        <div className="container mx-auto px-6">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="mb-4 md:mb-0">
              <h3 className="text-3xl font-bold">1500+</h3>
              <p className="text-lg">Number Of Supporters</p>
            </div>
            <div className="max-w-md">
              <h3 className="text-xl font-bold mb-4">Our Client Feedback</h3>
              <p className="mb-4">
                Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all,
                love of what you are doing or learning to do, perseverance, learning, studying, sacrifice and most of
                all, love.
              </p>
              <p className="font-semibold">Johnson</p>
              <p>CEO</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
